apiVersion: apps/v1
kind: Deployment
metadata:
  name: springops-app
  labels:
    app: springops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springops-app
  template:
    metadata:
      labels:
        app: springops-app
    spec:
      containers:
        - name: springops-app
          image: vathanaksol/springops:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: springops-app-service
  labels:
    app: springops-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: springops-app
