apiVersion: apps/v1
kind: Deployment
metadata: 
  name: basic-nextjs
  labels:
    app: basic-nextjs 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-nextjs
  template:
    metadata:
      labels: 
        app: basic-nextjs
    spec:
      containers:
        - name: basic-app
          image: vathanaksol/nextjs-kubernete:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: basic-nextjs-service
  labels:
    app: basic-nextjs
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  selector:
    app: basic-nextjs

